version: '3.8'

networks:
  dai-net:
    driver: bridge

services:
  static-web-server:
    build: src/main/java/server/web
    ports:
      - "80:80"

  postgresql:
    image: 'bitnami/postgresql:16'
    container_name: dai-lab-http-infrastructure
    environment:
      - POSTGRESQL_USERNAME=dai
      - POSTGRESQL_PASSWORD=dai
      - POSTGRESQL_DATABASE=dai
      - POSTGRESQL_POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - .:/data:ro
    networks:
      - dai-net

  api:
    #image: server-1.0-jar-with-dependencies.jar
    build:
      context: src/main/java/server/API
    ports:
      - "7000:7000"
